# render.toml

services:
  - type: web
    name: mini-rag-backend
    env: docker
    plan: free
    dockerfilePath: infra/Dockerfile.server
    autoDeploy: true
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

  - type: web
    name: mini-rag-frontend
    env: docker
    plan: free
    dockerfilePath: infra/Dockerfile.frontend
    autoDeploy: true
